// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpU54mDYz5WFYst_6MHNkrICSkBJSjmYY',
    appId: '1:329769199370:web:ba49fb1d3213ea53a67cf3',
    messagingSenderId: '329769199370',
    projectId: 'rinex-7142c',
    authDomain: 'rinex-7142c.firebaseapp.com',
    storageBucket: 'rinex-7142c.firebasestorage.app',
    measurementId: 'G-4H05S9HVQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxRV_FMmk8nU40oZEMlSGCp-ZSizWIZrQ',
    appId: '1:329769199370:android:24d504f8aa40be96a67cf3',
    messagingSenderId: '329769199370',
    projectId: 'rinex-7142c',
    storageBucket: 'rinex-7142c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUz5HVY3XfVzjiKYc022fXy_51BTpxZMU',
    appId: '1:329769199370:ios:7bb646c4d41a2df8a67cf3',
    messagingSenderId: '329769199370',
    projectId: 'rinex-7142c',
    storageBucket: 'rinex-7142c.firebasestorage.app',
    iosClientId: '329769199370-gr70fla84do2ib2965d4leqtr0o6vmv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.rinex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUz5HVY3XfVzjiKYc022fXy_51BTpxZMU',
    appId: '1:329769199370:ios:7bb646c4d41a2df8a67cf3',
    messagingSenderId: '329769199370',
    projectId: 'rinex-7142c',
    storageBucket: 'rinex-7142c.firebasestorage.app',
    iosClientId: '329769199370-gr70fla84do2ib2965d4leqtr0o6vmv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.rinex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpU54mDYz5WFYst_6MHNkrICSkBJSjmYY',
    appId: '1:329769199370:web:e59ef862951768e9a67cf3',
    messagingSenderId: '329769199370',
    projectId: 'rinex-7142c',
    authDomain: 'rinex-7142c.firebaseapp.com',
    storageBucket: 'rinex-7142c.firebasestorage.app',
    measurementId: 'G-07SR495FQC',
  );
}
